name: minimal-api-csharp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Install EF Tool
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-ef
    - name: Build dotnet bundle
      run: dotnet ef migrations bundle --verbose
    - name: Deploy the Database Changes
      # The bundle command will fail because it is pointing to my local development machine.
      # If you like to deploy - execute the following code. Since I removed the Azure Database, it is commented.
      # run: ./efbundle --connection ${{ secrets.CONNECTIONSTRING }}
      run: echo "Execute the following command to deploy the migrations - ./efbundle --connection <connection string>"
